### ISSUE TITLE
Params are not passed (hence neither the cmdline args)

### ISSUE THREAD

**Issue by marcoesposito1988** [Sahloul/ar_sys#1]
Hi Sahloul,

I tried to launch the single_board node with a custom marker size, but I noticed that the param still has the default value specified in the code (0.05).

The whole namespace thing might need a rework.

**Comment by bmcdorman** [comment]
I just encountered the same problem. To save someone else a few hours, the marker_size type should be double instead of string in the launch file.

`<param name="marker_size" type="string" value="$(arg marker_size)"/>`

should be

`<param name="marker_size" type="double" value="$(arg marker_size)"/>`
